import { ForecastState } from './types.ts';

export const FORECAST_STATES: ForecastState[] = [
  {
    id: 'T-36H',
    label: 'T-36H NOW',
    forecastHour: -36,
    windKmh: 185,
    rainfallMm: 220,
    stormSurgeM: 2.4,
    landfallDistanceKm: 12,
    estimatedRisk: 87,
    riskLevel: 'CRITICAL',
    floodExposure: 78,
    roadsExposed: 7,
    medicalExposed: 2,
    powerExposed: 4,
    sheltersExposed: 6,
    coordinates: { x: 820, y: 540, lat: 19.8, lng: 88.2 },
    operationalPhase: 'PHASE 1: PRE-LANDFALL STAGING & EVACUATION WARNINGS',
    actionSummary: 'Sector 04B on high watch. Issue early evacuation alerts for low-lying coastal hamlets.',
  },
  {
    id: 'T-24H',
    label: 'T-24H',
    forecastHour: -24,
    windKmh: 195,
    rainfallMm: 250,
    stormSurgeM: 2.6,
    landfallDistanceKm: 8,
    estimatedRisk: 90,
    riskLevel: 'CRITICAL',
    floodExposure: 83,
    roadsExposed: 9,
    medicalExposed: 2,
    powerExposed: 5,
    sheltersExposed: 7,
    coordinates: { x: 680, y: 450, lat: 20.1, lng: 87.6 },
    operationalPhase: 'PHASE 2: PRE-POSITIONING ASSETS & LOGISTICS',
    actionSummary: 'Move amphibious units to Dhamra corridor. Pre-position high-capacity dewatering pumps.',
  },
  {
    id: 'T-12H',
    label: 'T-12H',
    forecastHour: -12,
    windKmh: 205,
    rainfallMm: 290,
    stormSurgeM: 2.9,
    landfallDistanceKm: 4,
    estimatedRisk: 95,
    riskLevel: 'CRITICAL',
    floodExposure: 90,
    roadsExposed: 12,
    medicalExposed: 3,
    powerExposed: 6,
    sheltersExposed: 8,
    coordinates: { x: 520, y: 365, lat: 20.5, lng: 87.1 },
    operationalPhase: 'PHASE 3: RESTRICT ALL TRANSIT & MANDATORY SHELTERING',
    actionSummary: 'Close NH-516 arterial. Enforce mandatory sheltering. Generator fuel reserves secured.',
  },
  {
    id: 'LANDFALL',
    label: 'LANDFALL (T-0H)',
    forecastHour: 0,
    windKmh: 215,
    rainfallMm: 340,
    stormSurgeM: 3.2,
    landfallDistanceKm: 0,
    estimatedRisk: 98,
    riskLevel: 'CRITICAL',
    floodExposure: 96,
    roadsExposed: 15,
    medicalExposed: 4,
    powerExposed: 7,
    sheltersExposed: 9,
    coordinates: { x: 380, y: 285, lat: 20.8, lng: 86.9 },
    operationalPhase: 'PHASE 4: ACTIVE EYE IMPACT & TOTAL LOCKDOWN',
    actionSummary: 'Direct eye crossing Dhamra port corridor. Strict total movement prohibition across sectors.',
  },
  {
    id: 'POST-LANDFALL',
    label: 'POST-LANDFALL (T+6H)',
    forecastHour: 6,
    windKmh: 145,
    rainfallMm: 310,
    stormSurgeM: 1.8,
    landfallDistanceKm: 35,
    estimatedRisk: 74,
    riskLevel: 'HIGH',
    floodExposure: 84,
    roadsExposed: 11,
    medicalExposed: 3,
    powerExposed: 5,
    sheltersExposed: 7,
    coordinates: { x: 260, y: 210, lat: 21.2, lng: 86.4 },
    operationalPhase: 'PHASE 5: RAPID DAMAGE AUDIT & ARTERIAL CLEARANCE',
    actionSummary: 'Begin clearing arterial routes. Dewater flooded substations and perform patient extractions.',
  },
];
